In [1]:
import numpy as np 

# Numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [7]:
matrixListesi[1][0]

20

In [8]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange



In [9]:
list(range(0,10))#liste oluşturduk burada

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(list(range(0,10)))

list

In [11]:
np.arange(0,10)#burada ise bir dizi oluşturduk

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(np.arange(0,10))

numpy.ndarray

In [13]:
np.arange(0,20,2)#2 şer 2 şer artan şekilde dizi oluşturuyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros


In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [17]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

# eye

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# random

In [19]:
np.random.randn(8)

array([ 0.05478198,  0.56019967,  0.76931714,  0.22627661, -1.38526804,
       -0.40820242, -1.87254605,  0.12216718])

In [20]:
np.random.randn(4,4) #random matris oluşturma

array([[ 0.88305076,  1.15913233,  0.57299685,  0.33960924],
       [-1.8043461 ,  0.7028001 , -0.03004265, -0.66638341],
       [-0.04657207, -2.03243327, -0.70230844,  1.28395857],
       [ 0.51901892, -1.16880991, -0.2884965 , -1.41024   ]])

In [21]:
np.random.randint(1,10) #random sayı 10 dağil değil 

2

In [22]:
np.random.randint(1,300,5) # random 5 tane sayı

array([172, 269, 192, 164,  35])

In [23]:
benimRandomDizim=np.random.randint(0,100,30)

In [24]:
benimRandomDizim

array([ 9, 84,  0, 77, 50, 81, 77, 91,  3, 41, 63, 71, 12, 64,  0, 10,  3,
       98, 63, 98, 62, 69, 34, 71,  1, 72, 27, 22, 77, 81])

# numpy dizi metotları


In [25]:
benimRandomDizim.reshape(5,6)

array([[ 9, 84,  0, 77, 50, 81],
       [77, 91,  3, 41, 63, 71],
       [12, 64,  0, 10,  3, 98],
       [63, 98, 62, 69, 34, 71],
       [ 1, 72, 27, 22, 77, 81]])

In [26]:
benimRandomDizim.max()

98

In [27]:
benimRandomDizim.min()

0

In [28]:
benimRandomDizim.argmax()

17

In [29]:
benimRandomDizim.argmin()

2

In [30]:
benimRandomDizim

array([ 9, 84,  0, 77, 50, 81, 77, 91,  3, 41, 63, 71, 12, 64,  0, 10,  3,
       98, 63, 98, 62, 69, 34, 71,  1, 72, 27, 22, 77, 81])

In [31]:
benimRandomDizim.shape

(30,)

In [32]:
reshapeDizim=benimRandomDizim.reshape(5,6)

In [33]:
reshapeDizim

array([[ 9, 84,  0, 77, 50, 81],
       [77, 91,  3, 41, 63, 71],
       [12, 64,  0, 10,  3, 98],
       [63, 98, 62, 69, 34, 71],
       [ 1, 72, 27, 22, 77, 81]])

In [34]:
reshapeDizim.shape

(5, 6)

## Operasyonlar

In [35]:
benimDizim=np.arange(0,15)

In [36]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
benimDizim[5]

5

In [38]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [39]:
benimDizim[3:8]=-5

In [40]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [41]:
baskaDizi=np.arange(0,24)

In [42]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
slicingDizisi=baskaDizi[4:9]

In [44]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [45]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
slicingDizisi[:]=700

In [47]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [48]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [49]:
ornekDizi=np.arange(0,24)

In [50]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
ornekDiziKopyasi=ornekDizi.copy()

In [52]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [53]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
ornekDiziKopyasiSlicing=ornekDiziKopyasi[3:8]

In [55]:
ornekDiziKopyasiSlicing[:]=800

In [56]:
ornekDiziKopyasiSlicing

array([800, 800, 800, 800, 800])

In [57]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800, 800, 800,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [58]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix 

In [59]:
benimListem=[[10,20,30],[20,30,40],[30,40,50]]

In [60]:
benimMatrixDizim=np.array(benimListem)

In [61]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [62]:
benimMatrixDizim[0]

array([10, 20, 30])

In [63]:
benimMatrixDizim[1][2]

40

In [64]:
benimMatrixDizim[1,2]

40

In [65]:
benimMatrixDizim[0:,2]

array([30, 40, 50])

In [66]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [67]:
yeniMatrix=np.array(yeniListe)

In [68]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar 

In [70]:
yeniBirDizi=np.random.randint(1,100,20)

In [71]:
yeniBirDizi

array([20, 19, 39,  6, 54, 98, 71, 89, 17, 33, 31, 73, 77, 25,  7, 48, 93,
       47,  1, 88])

In [72]:
yeniBirDizi>24

array([False, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [73]:
sonucDizisi=yeniBirDizi>24

In [74]:
sonucDizisi

array([False, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [75]:
yeniBirDizi

array([20, 19, 39,  6, 54, 98, 71, 89, 17, 33, 31, 73, 77, 25,  7, 48, 93,
       47,  1, 88])

In [76]:
yeniBirDizi[sonucDizisi]

array([39, 54, 98, 71, 89, 33, 31, 73, 77, 25, 48, 93, 47, 88])

In [77]:
sonDizi=np.arange(0,24)

In [78]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [80]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [81]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [82]:
sonDizi- sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [83]:
sonDizi/sonDizi

C:\Users\emirc\AppData\Local\Temp\ipykernel_3908\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
np.sqrt(sonDizi) ##karakök alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [85]:
np.max(sonDizi)

23

In [86]:
np.min(sonDizi)

0

In [87]:
https://numpy.org/

SyntaxError: invalid syntax (1462981225.py, line 1)