In [5]:
import numpy as np 

# Numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [6]:
np.array(benimListem)

array([20, 30, 40])

In [7]:
type(np.array(benimListem))

numpy.ndarray

In [8]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [9]:
matrixListesi[1][0]

20

In [10]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange



In [15]:
list(range(0,10))#liste oluşturduk burada

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
type(list(range(0,10)))

list

In [12]:
np.arange(0,10)#burada ise bir dizi oluşturduk

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
type(np.arange(0,10))

numpy.ndarray

In [14]:
np.arange(0,20,2)#2 şer 2 şer artan şekilde dizi oluşturuyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros


In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace